/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.drools.test;


import mock.MockFact;
import org.drools.mas.util.LoggerHelper;


rule "Log"
when
    $o : Object()
then 
    LoggerHelper.info(" >>> FAILURE SESSION >>> " + $o);
end

rule "Insert a MockFact"
when
    $s: String( this str[startsWith] "insert MockFact please")
then
    LoggerHelper.info(" >>> I'M ABOUT TO INSERT NEW MockFact");
    insert(new MockFact($s, 18));
end

rule "RHS Fail"
when
    String( this == "fail please")
then
    LoggerHelper.info(" >>> SESSION IS ABOUT TO FAIL");
    throw new RuntimeException("Explicitly thrown Exception");
end

rule "LHS Fail"
when
    MockFact(name.length == 1)
then
    LoggerHelper.info(" >>> MockFact with name length = 1 found!");
end
