/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
    Domain-Specific, concrete routing rules.
    Can exploit JsonPath / XPath queries on a message's
    encoded form for type-unsafe checks, in addition to
    standard pattern matching on a message content
    represented in object form

*/

package org.drools.mas.failure.main; //this is completly wrong.. we need to use the same package as core to use the mapSession query


import org.drools.mas.ACLMessage;
import org.drools.mas.util.ACLMessageFactory;
import org.drools.mas.body.acts.*;
import org.drools.mas.body.content.Info;
import org.drools.mas.util.InspectMessageHelper;
import mock.MockFact;
import org.drools.mas.Act;
import org.drools.mas.core.Destination;
import org.drools.mas.core.SessionMapping;
import org.drools.mas.core.MappingLookup;
import org.drools.mas.Encodings;
import org.drools.mas.util.LoggerHelper;


global String globalString;

rule "Mapping"
when
then
    insert( new SessionMapping( "subsession", "fail-sub" ) );
end


rule "Route_Encoded"
salience -1
when
    $msg : ACLMessage( $msgId : id, $b : body, encoding == Encodings.JSON  )
then
    LoggerHelper.debug(" ### Example CBR: Routing message J " + $msgId  );
    insert( new MappingLookup( $msgId, "subsession" ) );
end

rule "Route_Encoded_X"
salience -1
when
    $msg : ACLMessage( $msgId : id, $b : body, encoding == Encodings.XML )
then
    LoggerHelper.debug(" ### Example CBR: Routing message  X " + $msgId  );
    insert( new MappingLookup( $msgId, "subsession" ) );
end




