
package org.drools.mas.helpers;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.drools.mas.ACLMessage;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AsyncDroolsAgentService", targetNamespace = "http://mas.drools.org/")
@XmlSeeAlso({
    org.drools.mas.helpers.ObjectFactory.class
})
public interface AsyncDroolsAgentService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "tell", targetNamespace = "http://helpers.mas.drools.org/", className = "org.drools.mas.Tell")
    @ResponseWrapper(localName = "tellResponse", targetNamespace = "http://helpers.mas.drools.org/", className = "org.drools.mas.helpers.TellResponse")
    public void tell(
        @WebParam(name = "arg0", targetNamespace = "")
        ACLMessage arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.drools.mas.ACLMessage>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResponses", targetNamespace = "http://helpers.mas.drools.org/", className = "org.drools.mas.helpers.GetResponses")
    @ResponseWrapper(localName = "getResponsesResponse", targetNamespace = "http://helpers.mas.drools.org/", className = "org.drools.mas.helpers.GetResponsesResponse")
    public List<ACLMessage> getResponses(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
