
package org.drools.mas.helpers;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SynchronousDroolsAgentServiceImplService", targetNamespace = "http://mas.drools.org/", wsdlLocation = "http://localhost:8080/agent/services/?WSDL")
public class SynchronousDroolsAgentServiceImplService
    extends Service
{

    private final static URL SYNCHRONOUSDROOLSAGENTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.drools.mas.helpers.SynchronousDroolsAgentServiceImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.drools.mas.helpers.SynchronousDroolsAgentServiceImplService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/agent/services/?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/agent/services/?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SYNCHRONOUSDROOLSAGENTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
    }

    public SynchronousDroolsAgentServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SynchronousDroolsAgentServiceImplService() {
        super(SYNCHRONOUSDROOLSAGENTSERVICEIMPLSERVICE_WSDL_LOCATION, new QName("http://mas.drools.org/", "SynchronousDroolsAgentServiceImplService"));
    }

    /**
     * 
     * @return
     *     returns SynchronousDroolsAgentService
     */
    @WebEndpoint(name = "SynchronousDroolsAgentServiceImplPort")
    public SynchronousDroolsAgentService getSynchronousDroolsAgentServiceImplPort() {
        return super.getPort(new QName("http://mas.drools.org/", "SynchronousDroolsAgentServiceImplPort"), SynchronousDroolsAgentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SynchronousDroolsAgentService
     */
    @WebEndpoint(name = "SynchronousDroolsAgentServiceImplPort")
    public SynchronousDroolsAgentService getSynchronousDroolsAgentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mas.drools.org/", "SynchronousDroolsAgentServiceImplPort"), SynchronousDroolsAgentService.class, features);
    }

}
