/**
  Content Based routing general rules
  When a message arrives, CBR rules determine its destination (the session(s) where it needs to be processed),
  while processing rules determine the commands to be executed to deliver the contents to that session.
  When the two steps have been completed, the commands are delivered.
*/

package org.drools.fipa;
import org.drools.fipa.core.SessionManager;
import org.drools.fipa.body.content.ActionHolder;
import org.drools.fipa.body.content.Action;

// KnowledgeAgent wrapper used to modify the KB on the fly
global SessionManager manager;






query queryIf( Object $o )
    $queryIf : Object( this == $o )
end


rule "Delayed action"
salience 9999
when
    $holder : ActionHolder( $id : refId, $act : action, $drl : condition)
then
    manager.addRuleByTemplate("FIPA_RWH_"+$id, "requestWhen.drlt", $holder);
end







