/*
    Common declarations for Drools Agents
*/

package org.drools.mas;
import org.drools.mas.ACLMessage;
import org.drools.command.Command;
import org.drools.command.BatchExecutionCommand;
import org.drools.runtime.StatefulKnowledgeSession;
import java.util.Map;

import org.drools.base.*;
import org.drools.mas.body.acts.*;
import org.drools.mas.body.content.Action;
import org.drools.mas.AgentID;

// ACL message factory, to generate responses
global org.drools.mas.util.ACLMessageFactory aclFactory;

// Agent name
global AgentID agentName;

// References to slave sessions
global Map proxies;

// ChangeSet for dynamically generated subsessions
global String defaultCS;


// messages are declared events to handle timestamping
declare ACLMessage
    @role(event)
end



// reference between a message and the commands to process that message content in a remote session
declare MessageCommands
    msgId : String
    cmd : Command
end

declare OneShotMessageCommand
    msgId : String
    payload : Command
end

// custom mapping between sessions and domain-specific identifiers (e.g. patient id)
declare SessionMapping
    key : String
    sessionId : String
end

// association between a message and the session where its contents are to be processed
declare Destination
    messageId : String
    sessionId : String
end

declare ResponseContent
@typesafe(false)
    messageId : String
    data : Object
end

declare PerformativeFail
    messageId : String
    cause     : Exception
end




