package org.drools.mas;

import org.drools.mas.body.content.*;
import org.drools.mas.action.message.*;
import org.drools.mas.action.message.types.*;
import org.drools.mas.action.message.invokers.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.Date;

import org.drools.mas.action.helpers.*;


import javax.xml.ws.BindingProvider;





rule "Say Hello"
when
    $o: Object()
then
    System.out.println("Hi this is the Agent One, Saying Hello -> "+$o);
end