/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.drools.mas.test.test1;


import mock.MockFact;
import org.slf4j.Logger;
import org.drools.mas.util.LoggerHelper;

import org.drools.core.io.impl.UrlResource;
import org.kie.api.io.Resource;
import java.net.URL;
import org.kie.api.io.ResourceType;

global String session1GlobalString;

query ageOfPatient( MockFact $mock, String $patientName, int $age )
    $mock := MockFact( $patientName := name, $age := age )
end

rule "Log"
when
    $o : Object()
then 
    LoggerHelper.info(" >>> SESSION #1 >>> " + $o);
end


query exceptional( )
end



