/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
  Contains rules to handle the internal sessions that an agent can have.
*/

package org.drools.mas.core;

import org.drools.mas.util.helper.SessionLocator
import org.drools.mas.util.LoggerHelper;

query "getSessionById"(String id)
    $sessionLocator: SessionLocator(sessionId == id)
end
query "getSessions"()
    $sessionLocator: SessionLocator()
end

rule "Log Session Session Locator Entry"
    when
        SessionLocator( $sessionId: sessionId )
    then
        if( LoggerHelper.isDebugEnabled() ) {
            LoggerHelper.debug(" ### New Session Locator Entry - sessionId: " + $sessionId );
        }
end
            