package org.drools.mas;

import org.drools.mas.body.content.*;
import org.drools.mas.action.message.*;
import org.drools.mas.action.message.types.*;
import org.drools.mas.action.message.invokers.*;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.Date;
import org.drools.mas.util.MessageContentEncoder;
import org.drools.mas.action.helpers.*;
import org.drools.mas.util.helper.*;
import org.drools.mas.core.helpers.*;
import org.drools.mas.examples.emergency.*;


rule "Generic Knowledge Adquisition"
when
    $o: Object()
then
    System.out.println( "Now I know about this: >>> " + $o );
end

rule "Coordinate Emergency Action Processing"
salience 1
when
    $action: Action( actionName == "coordinateEmergency" )
then
    System.out.println( "Coordinating Emergency ->"+$action );
    insert( new Actions( "Sending Ambulances", "Sending Firefigthers" ) );
end


query coordinateEmergency( Actions $ret )
    $ret:= Actions()
end

rule "Response collector - deliverMessage"
when
    $s : SessionLocator( $sessionId: sessionId, mind == true )
    $action: Action( actionName == "coordinateEmergency",  $msgId: msgId )
    coordinateEmergency( $return; )
then
    retract( $action );
    ResponseContent.deliverResponse( $sessionId, $msgId, $return, null );
end



















